spring:
  application:
    name: "jwt-security"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    jdbc-url: ${spring.datasource.url}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
token:
  signing:
    key: ${SECRET_KEY}
